maintenance
fingerprintjs/fingerprintjs-pro-react-native pull request #113
Opened 2024-03-27 15:18 UTC by necipallef

- disabled Flipper according to [this comment](https://github.com/facebook/react-native/issues/43335#issuecomment-1980788427).
- overall improvements on docs
- refactored tests

2024-03-27 20:17 UTC, necipallef commented
I've just updated Rollup. After running `yarn build` with the old and new config, the diff are minimal, I've attached screenshots of them. Also, no diff exists for `fpjs-pro-react-native.esm.js` file.
![fpjs-pro-react-native d ts diff ](https://github.com/fingerprintjs/fingerprintjs-pro-react-native/assets/11958773/e60d0367-cfc1-41e3-aa1b-0ab5cc771f1a)
![fpjs-pro-react-native cjs js diff](https://github.com/fingerprintjs/fingerprintjs-pro-react-native/assets/11958773/ea9ebfe8-31ac-4249-b431-8c178f9b2bf1)

2024-03-28 13:32 UTC, ilfa requested changes

2024-03-28 13:40 UTC, necipallef commented on package.json
>      "@types/jest": "^27.4.1",
Done. Could you check again, please? @ilfa

2024-03-28 14:12 UTC, ilfa approved these changes

2024-03-28 14:36 UTC, mgutski commented on contributing.md
>  4. Run `yarn start`. From this moment it will keep your terminal.
For consistency, you could also update the numbering for the last two steps.

2024-03-28 14:38 UTC, mgutski approved these changes

2024-03-28 14:41 UTC, necipallef commented on contributing.md
>  4. Run `yarn start`. From this moment it will keep your terminal.
That is quite painful because each time we add an item, we need to set all numbers again. Thankfully, GitHub does not care about what actual numbers are, it will automatically use indices. I'd like to set all to `1` in next iteration. Thanks for the heads up!

2024-03-28 14:41 UTC, merged